### PR TITLE
Player movement

### PR DESCRIPTION
**Pull request by EdwardAndress**
This is partly to start a conversation about how we deal with the experimental work we're initially doing.  Does it get merged into master?  If not, how do we consolidate our various experiments?  I think it probably should go into master but at what point is the work good enough?

What do you think?

### CODE REVIEW

**Comment by EdwardAndress** [comment]
If it's to go onto master, we should hold off merging until I have bottomed out the plugin issue.

**Comment by jimnarey** [comment]
Let's keep a 'working' or other such branch, for a bit of separation from master.

**Comment by EdwardAndress** [comment]
dev branch?

**Comment by jimnarey** [comment]
Yes. It seems a bit over-engineered for two of us but is better than the alternative.

**Pull request closed without merging**
