### PR TITLE
Try player class

### PR DESCRIPTION
**Pull request by jimnarey**
Game is now a class.

Player is now a class, with pretty much all the relevant functionality moved over. Really this should be a 'Character' class which is then extended, as much of it will be the same for enemies.

This then needs the Weapon Plugin stuff moving back. The other headache is that the sprite is not showing the image (texture)! You can see in the constructor what I've tried to resolve this.

### CODE REVIEW

**Comment by jimnarey** [comment]
I tried extending Image instead of Sprite, but no luck.

**Comment by EdwardAndress** [comment]
Despite the issue with the texture, this looks like good progress.

**Comment by jimnarey** [comment]
I think this is ready to go into our new dev branch. I'll start having a look at getting your weapon work into this new structure.

**Review by EdwardAndress — APPROVED** [review]
Looks great!  I especially like the way we're now delegating player movement to the player class.

**Pull request merged**
